[package]
name = "M0TH3RAT3"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.1"
color-eyre = "0.6.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
ratatui = "0.27.0"
strum = { version = "0.26.3", features = ["strum_macros"] }
